from jinja2 import DictLoader, Environment
from volt.generator import _generate


def test_generate():
    templates = {
        "about.html": """
{% extends "base.html" %}

{% block content %}
{{ bar }}
{% endblock %}
""",
        "base.html": """
{{ foo }}
{% block content %}
{% endblock %}
""",
    }
    environment = Environment(loader=DictLoader(templates))
    output = _generate(environment, import_types=True)
    print(output)
    expected_output = """# pyright: basic
\"\"\"
This file is automatically generated.
Do not edit this file directly.
\"\"\"
from dataclasses import dataclass

from volt.components import Component

from custom_types import (
    AboutContentTypes,
)


class BaseContent(Component):
    template_name: str = "base.html"
    block_name: str = "content"

    @dataclass
    class Context(Component.Context):
        ...

    def __init__(self, context: Context) -> None:
        super().__init__(context)


class Base(BaseContent):
    template_name: str = "base.html"
    block_name: str = "content"

    @dataclass
    class Context(BaseContent.Context):
        ...

    def __init__(self, context: Context) -> None:
        super().__init__(context)


class AboutContent(Base):
    template_name: str = "about.html"
    block_name: str = "content"

    @dataclass
    class Context(Base.Context):
        bar: AboutContentTypes.bar

    def __init__(self, context: Context) -> None:
        super().__init__(context)


class About(AboutContent):
    template_name: str = "about.html"
    block_name: str = "content"

    @dataclass
    class Context(AboutContent.Context):
        ...

    def __init__(self, context: Context) -> None:
        super().__init__(context)

"""
    assert output == expected_output
