# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
# source: query.sql
from typing import Optional

import sqlalchemy

from db import models


GET_VOLT = """-- name: get_volt \\:one
SELECT id, stuff
FROM volt
WHERE 
	volt.id = :p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_volt(self, *, id: int) -> Optional[models.Volt]:
        row = self._conn.execute(sqlalchemy.text(GET_VOLT), {"p1": id}).first()
        if row is None:
            return None
        return models.Volt(
            id=row[0],
            stuff=row[1],
        )
