name: Build and Publish Wheels

on: 
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - macos-13  # for x86 support # Not supported, takes too long to build in GA
          # - windows-latest # Not supported, zig code needs rework
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      - name: Install build tools
        run: pip install build
      
      - name: Build Zig binary
        run: zig build -Doptimize=ReleaseFast --prefix volt
      
      - name: Build wheel
        run: python -m build --wheel
      
      - name: Check wheel
        run: |
          pip install twine
          twine check dist/*
      
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: dist/*.whl
          retention-days: 7

  # Upload to Test PyPI on every push to main
  upload_test_pypi:
    name: Upload to Test PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi-test
      url: https://test.pypi.org/project/volt-framework/
    permissions:
      id-token: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          merge-multiple: true
          path: dist
      
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  # Upload to production PyPI only on releases
  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/volt-framework/
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          merge-multiple: true
          path: dist
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
